### ISSUE TITLE
show proper errors (new designs)

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#122]
there are new designs for some errors:

 - [x] problem loading bookings: [Zeplin](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5adf1de8c47dfd34776d3a95)
 - [x] problem with credentials on kiwi login: [Zeplin](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5ade109e2fd3d795017aeaba)
- [x] no results for faqs search: [Zeplin](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5adf5b6edd2effba0e15cf34)

**Comment by jalbertsr** [comment]
test: https://kiwicom.github.io/smart-faq/

**Comment by MagdalenaAlmanova** [comment]
I do not know, how I can test the first error page  "problem loading booking". Do you have some tips for this? 

The first mistake was in the error page "problem with credentials on kiwi login" **the ! symbol** was not like in the design. It is smaller. 
**Demo v.**
![screen shot 2018-05-02 at 11 17 57](https://user-images.githubusercontent.com/37298895/39543980-f79cfabe-4e4c-11e8-9e88-774cbf69a9a7.png)
**_Prototype v._**
![screen shot 2018-05-02 at 21 00 23](https://user-images.githubusercontent.com/37298895/39543998-080790c6-4e4d-11e8-95b2-73a1cd626a16.png)
The second mistake was in the third error page. Only in Opera, the text "your search didn't match .... and Maybe, consider one of... " wasn't **bold.**
![screen shot 2018-05-02 at 21 04 20](https://user-images.githubusercontent.com/37298895/39544193-94d3711e-4e4d-11e8-86e3-e14a9916231b.png)

From now, I will test on https://introduce-smart-faq.fe.staging.kiwi.com/en/ 

Thanks,
Meggy

**Comment by git-toni** [comment]
> I do not know, how I can test the first error page "problem loading booking". Do you have some tips for this?

I think you can try to disable wi-fi quickly right after clicking on the page?  Best luck!  :smile:

**Comment by MagdalenaAlmanova** [comment]
Thank you for your tip, I used it and it worked :D I think, that the first page is same as the design 💯 

Two mistakes are still persistent, please look at it. 

Meggy

**Comment by jalbertsr** [comment]
with the new updated orbit components, the alert symbol size problem should be resolved and about the bold text in opera, it is actually bold, but this is how opera renders bold for this text sizes...

**Comment by MagdalenaAlmanova** [comment]
I cannot find out this, because when I typed incorrect credentials, it showed me this: 
![screen shot 2018-05-14 at 15 10 20](https://user-images.githubusercontent.com/37298895/39999269-fb3b1062-5788-11e8-93bd-715f11bebe39.png)

It is on https://introduce-smart-faq.fe.staging.kiwi.com/en/

**Comment by MagdalenaAlmanova** [comment]
Two things: The first one is about "problem with credentials on kiwi login". **The font thickness** is different and I think, that the text is not **aligned** (is slightly higher).
Demo v.
![screen shot 2018-05-31 at 21 54 56](https://user-images.githubusercontent.com/37298895/40805555-e7f047a4-651e-11e8-910c-eafa10260068.png)
Prototype v.
![screen shot 2018-05-31 at 21 55 10](https://user-images.githubusercontent.com/37298895/40805568-f4f4cc5e-651e-11e8-9045-500cf8fc1f0d.png)
The second one is about **missing bullet points** in "no results for faqs search" and **font thickness** in the first sentences is different. 
Demo v.
![screen shot 2018-05-31 at 21 59 30](https://user-images.githubusercontent.com/37298895/40805878-010cb80c-6520-11e8-9cda-eed1cd2faad0.png)
Prototype v.
![screen shot 2018-05-31 at 21 59 54](https://user-images.githubusercontent.com/37298895/40805887-077e9ef8-6520-11e8-9ecd-b1cc526adf5c.png)

Thanks.

**Comment by MagdalenaAlmanova** [comment]
These bugs are still persistent. I tried on kiwi.com. 
![screen shot 2018-06-12 at 22 20 13](https://user-images.githubusercontent.com/37298895/41315081-d249c99c-6e8e-11e8-969c-1dae93526a8b.png)

@jalbertsr

**Comment by jalbertsr** [comment]
true, thanks for the reminder, I'll put it in the todo section.

**Comment by kantord** [comment]
@jalbertsr did you put it in todo in the end?

**Comment by vborszeki** [comment]
@MagdalenaAlmanova in the [standalone app](https://kiwicom.github.io/smart-faq/?help=%2Ffaq%2F) the error message and the list elements are rendered correctly now.
